package com.schindler.ioee.tm_service.mybatis.mapper;

import com.schindler.ioee.tm_service.mybatis.model.EquipmentOnlineStatus;
import com.schindler.ioee.tm_service.mybatis.model.EquipmentOnlineStatusExample.Criteria;
import com.schindler.ioee.tm_service.mybatis.model.EquipmentOnlineStatusExample.Criterion;
import com.schindler.ioee.tm_service.mybatis.model.EquipmentOnlineStatusExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

/**
 * @author litim
 */
public class EquipmentOnlineStatusSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EquipmentOnlineStatus
     *
     * @mbg.generated Fri Nov 15 15:58:21 CST 2019
     */
    public String countByExample(EquipmentOnlineStatusExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("EquipmentOnlineStatus");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EquipmentOnlineStatus
     *
     * @mbg.generated Fri Nov 15 15:58:21 CST 2019
     */
    public String deleteByExample(EquipmentOnlineStatusExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("EquipmentOnlineStatus");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EquipmentOnlineStatus
     *
     * @mbg.generated Fri Nov 15 15:58:21 CST 2019
     */
    public String insertSelective(EquipmentOnlineStatus record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("EquipmentOnlineStatus");
        
        if (record.getEquipmentId() != null) {
            sql.VALUES("EquipmentId", "#{equipmentId,jdbcType=VARCHAR}");
        }
        
        if (record.getContractNo() != null) {
            sql.VALUES("ContractNo", "#{contractNo,jdbcType=VARCHAR}");
        }
        
        if (record.getCubeNo() != null) {
            sql.VALUES("CubeNo", "#{cubeNo,jdbcType=VARCHAR}");
        }
        
        if (record.getTechnician() != null) {
            sql.VALUES("Technician", "#{technician,jdbcType=VARCHAR}");
        }
        
        if (record.getPhoneNumber() != null) {
            sql.VALUES("PhoneNumber", "#{phoneNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            sql.VALUES("Email", "#{email,jdbcType=VARCHAR}");
        }
        
        if (record.getNotifyTime() != null) {
            sql.VALUES("NotifyTime", "#{notifyTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getHeartbeatTime() != null) {
            sql.VALUES("HeartbeatTime", "#{heartbeatTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateDate() != null) {
            sql.VALUES("CreateDate", "#{createDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateBy() != null) {
            sql.VALUES("CreateBy", "#{createBy,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateDate() != null) {
            sql.VALUES("UpdateDate", "#{updateDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateBy() != null) {
            sql.VALUES("UpdateBy", "#{updateBy,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EquipmentOnlineStatus
     *
     * @mbg.generated Fri Nov 15 15:58:21 CST 2019
     */
    public String selectByExample(EquipmentOnlineStatusExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("EquipmentId");
        } else {
            sql.SELECT("EquipmentId");
        }
        sql.SELECT("ContractNo");
        sql.SELECT("CubeNo");
        sql.SELECT("Technician");
        sql.SELECT("PhoneNumber");
        sql.SELECT("Email");
        sql.SELECT("NotifyTime");
        sql.SELECT("HeartbeatTime");
        sql.SELECT("CreateDate");
        sql.SELECT("CreateBy");
        sql.SELECT("UpdateDate");
        sql.SELECT("UpdateBy");
        sql.FROM("EquipmentOnlineStatus");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EquipmentOnlineStatus
     *
     * @mbg.generated Fri Nov 15 15:58:21 CST 2019
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        EquipmentOnlineStatus record = (EquipmentOnlineStatus) parameter.get("record");
        EquipmentOnlineStatusExample example = (EquipmentOnlineStatusExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("EquipmentOnlineStatus");
        
        if (record.getEquipmentId() != null) {
            sql.SET("EquipmentId = #{record.equipmentId,jdbcType=VARCHAR}");
        }
        
        if (record.getContractNo() != null) {
            sql.SET("ContractNo = #{record.contractNo,jdbcType=VARCHAR}");
        }
        
        if (record.getCubeNo() != null) {
            sql.SET("CubeNo = #{record.cubeNo,jdbcType=VARCHAR}");
        }
        
        if (record.getTechnician() != null) {
            sql.SET("Technician = #{record.technician,jdbcType=VARCHAR}");
        }
        
        if (record.getPhoneNumber() != null) {
            sql.SET("PhoneNumber = #{record.phoneNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            sql.SET("Email = #{record.email,jdbcType=VARCHAR}");
        }
        
        if (record.getNotifyTime() != null) {
            sql.SET("NotifyTime = #{record.notifyTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getHeartbeatTime() != null) {
            sql.SET("HeartbeatTime = #{record.heartbeatTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateDate() != null) {
            sql.SET("CreateDate = #{record.createDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateBy() != null) {
            sql.SET("CreateBy = #{record.createBy,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateDate() != null) {
            sql.SET("UpdateDate = #{record.updateDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateBy() != null) {
            sql.SET("UpdateBy = #{record.updateBy,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EquipmentOnlineStatus
     *
     * @mbg.generated Fri Nov 15 15:58:21 CST 2019
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("EquipmentOnlineStatus");
        
        sql.SET("EquipmentId = #{record.equipmentId,jdbcType=VARCHAR}");
        sql.SET("ContractNo = #{record.contractNo,jdbcType=VARCHAR}");
        sql.SET("CubeNo = #{record.cubeNo,jdbcType=VARCHAR}");
        sql.SET("Technician = #{record.technician,jdbcType=VARCHAR}");
        sql.SET("PhoneNumber = #{record.phoneNumber,jdbcType=VARCHAR}");
        sql.SET("Email = #{record.email,jdbcType=VARCHAR}");
        sql.SET("NotifyTime = #{record.notifyTime,jdbcType=TIMESTAMP}");
        sql.SET("HeartbeatTime = #{record.heartbeatTime,jdbcType=TIMESTAMP}");
        sql.SET("CreateDate = #{record.createDate,jdbcType=TIMESTAMP}");
        sql.SET("CreateBy = #{record.createBy,jdbcType=VARCHAR}");
        sql.SET("UpdateDate = #{record.updateDate,jdbcType=TIMESTAMP}");
        sql.SET("UpdateBy = #{record.updateBy,jdbcType=VARCHAR}");
        
        EquipmentOnlineStatusExample example = (EquipmentOnlineStatusExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EquipmentOnlineStatus
     *
     * @mbg.generated Fri Nov 15 15:58:21 CST 2019
     */
    public String updateByPrimaryKeySelective(EquipmentOnlineStatus record) {
        SQL sql = new SQL();
        sql.UPDATE("EquipmentOnlineStatus");
        
        if (record.getContractNo() != null) {
            sql.SET("ContractNo = #{contractNo,jdbcType=VARCHAR}");
        }
        
        if (record.getCubeNo() != null) {
            sql.SET("CubeNo = #{cubeNo,jdbcType=VARCHAR}");
        }
        
        if (record.getTechnician() != null) {
            sql.SET("Technician = #{technician,jdbcType=VARCHAR}");
        }
        
        if (record.getPhoneNumber() != null) {
            sql.SET("PhoneNumber = #{phoneNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            sql.SET("Email = #{email,jdbcType=VARCHAR}");
        }
        
        if (record.getNotifyTime() != null) {
            sql.SET("NotifyTime = #{notifyTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getHeartbeatTime() != null) {
            sql.SET("HeartbeatTime = #{heartbeatTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateDate() != null) {
            sql.SET("CreateDate = #{createDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateBy() != null) {
            sql.SET("CreateBy = #{createBy,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateDate() != null) {
            sql.SET("UpdateDate = #{updateDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateBy() != null) {
            sql.SET("UpdateBy = #{updateBy,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("EquipmentId = #{equipmentId,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EquipmentOnlineStatus
     *
     * @mbg.generated Fri Nov 15 15:58:21 CST 2019
     */
    protected void applyWhere(SQL sql, EquipmentOnlineStatusExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}