package com.schindler.ioee.tm_service.mybatis.mapper;

import com.schindler.ioee.tm_service.mybatis.model.User;
import com.schindler.ioee.tm_service.mybatis.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

/**
 * @author litim
 */
public interface UserMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated Mon Nov 18 11:02:18 CST 2019
     * @param example
     * @return
     */
    @SelectProvider(type=UserSqlProvider.class, method="countByExample")
    long countByExample(UserExample example);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated Mon Nov 18 11:02:18 CST 2019
     * @param example
     * @return
     */
    @DeleteProvider(type=UserSqlProvider.class, method="deleteByExample")
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated Mon Nov 18 11:02:18 CST 2019
     * @param userName
     * @return
     */
    @Delete({
        "delete from User",
        "where UserName = #{userName,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated Mon Nov 18 11:02:18 CST 2019
     * @param record
     * @return
     */
    @Insert({
        "insert into User (UserName, Password, ",
        "Nickname, Email, ",
        "CreateDate, UpdateDate)",
        "values (#{userName,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{nickname,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, ",
        "#{createDate,jdbcType=TIMESTAMP}, #{updateDate,jdbcType=TIMESTAMP})"
    })
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated Mon Nov 18 11:02:18 CST 2019
     * @param record
     * @return
     */
    @InsertProvider(type=UserSqlProvider.class, method="insertSelective")
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated Mon Nov 18 11:02:18 CST 2019
     * @param example
     * @param rowBounds
     * @return
     */
    @SelectProvider(type=UserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="UserName", property="userName", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="Password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="Nickname", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="Email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="CreateDate", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UpdateDate", property="updateDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<User> selectByExampleWithRowbounds(UserExample example, RowBounds rowBounds);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated Mon Nov 18 11:02:18 CST 2019
     * @param example
     * @return
     */
    @SelectProvider(type=UserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="UserName", property="userName", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="Password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="Nickname", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="Email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="CreateDate", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UpdateDate", property="updateDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<User> selectByExample(UserExample example);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated Mon Nov 18 11:02:18 CST 2019
     * @param userName
     * @return
     */
    @Select({
        "select",
        "UserName, Password, Nickname, Email, CreateDate, UpdateDate",
        "from User",
        "where UserName = #{userName,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="UserName", property="userName", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="Password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="Nickname", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="Email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="CreateDate", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UpdateDate", property="updateDate", jdbcType=JdbcType.TIMESTAMP)
    })
    User selectByPrimaryKey(String userName);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated Mon Nov 18 11:02:18 CST 2019
     * @param record
     * @param example
     * @return
     */
    @UpdateProvider(type=UserSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated Mon Nov 18 11:02:18 CST 2019
     * @param record
     * @param example
     * @return
     */
    @UpdateProvider(type=UserSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated Mon Nov 18 11:02:18 CST 2019
     * @param record
     * @return
     */
    @UpdateProvider(type=UserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(User record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated Mon Nov 18 11:02:18 CST 2019
     * @param record
     * @return
     */
    @Update({
        "update User",
        "set Password = #{password,jdbcType=VARCHAR},",
          "Nickname = #{nickname,jdbcType=VARCHAR},",
          "Email = #{email,jdbcType=VARCHAR},",
          "CreateDate = #{createDate,jdbcType=TIMESTAMP},",
          "UpdateDate = #{updateDate,jdbcType=TIMESTAMP}",
        "where UserName = #{userName,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(User record);
}